#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharpAlg.Android.Resource", IsApplication=true)]

namespace SharpAlg.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = SharpAlg.Android.Resource.Id.OptionHostName;
			Xamarin.Android.NUnitLite.Resource.Id.OptionPort = SharpAlg.Android.Resource.Id.OptionPort;
			Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = SharpAlg.Android.Resource.Id.OptionRemoteServer;
			Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = SharpAlg.Android.Resource.Id.OptionsButton;
			Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = SharpAlg.Android.Resource.Id.ResultFullName;
			Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = SharpAlg.Android.Resource.Id.ResultMessage;
			Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = SharpAlg.Android.Resource.Id.ResultResultState;
			Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = SharpAlg.Android.Resource.Id.ResultStackTrace;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = SharpAlg.Android.Resource.Id.ResultsFailed;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsId = SharpAlg.Android.Resource.Id.ResultsId;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = SharpAlg.Android.Resource.Id.ResultsIgnored;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = SharpAlg.Android.Resource.Id.ResultsInconclusive;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = SharpAlg.Android.Resource.Id.ResultsMessage;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = SharpAlg.Android.Resource.Id.ResultsPassed;
			Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = SharpAlg.Android.Resource.Id.ResultsResult;
			Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = SharpAlg.Android.Resource.Id.RunTestsButton;
			Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = SharpAlg.Android.Resource.Id.TestSuiteListView;
			Xamarin.Android.NUnitLite.Resource.Layout.options = SharpAlg.Android.Resource.Layout.options;
			Xamarin.Android.NUnitLite.Resource.Layout.results = SharpAlg.Android.Resource.Layout.results;
			Xamarin.Android.NUnitLite.Resource.Layout.test_result = SharpAlg.Android.Resource.Layout.test_result;
			Xamarin.Android.NUnitLite.Resource.Layout.test_suite = SharpAlg.Android.Resource.Layout.test_suite;
			SharpAlg.Core.Resource.Drawable.monoandroidsplash = SharpAlg.Android.Resource.Drawable.monoandroidsplash;
			SharpAlg.Core.Resource.String.ApplicationName = SharpAlg.Android.Resource.String.ApplicationName;
			SharpAlg.Core.Resource.String.Hello = SharpAlg.Android.Resource.String.Hello;
			SharpAlg.Core.Resource.Style.Mono_Android_Theme_Splash = SharpAlg.Android.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int OptionHostName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int OptionPort = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int OptionRemoteServer = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int OptionsButton = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int ResultFullName = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int ResultMessage = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int ResultResultState = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int ResultStackTrace = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int ResultsFailed = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ResultsId = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ResultsIgnored = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int ResultsInconclusive = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ResultsMessage = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int ResultsPassed = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int ResultsResult = 2131099652;
			
			// aapt resource value: 0x7f06000f
			public const int RunTestsButton = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int TestSuiteListView = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
