/*Generated by SharpKit 5 v5.01.1000*/
function DefaultClient_Load()
{
    Compile();
};
function btnTest_click(e)
{
    RunTests();
};
function RunTests()
{
    var fixtures = [new SharpAlg.Tests.ExprTests.ctor(), new SharpAlg.Tests.ParserTests.ctor()];
    var jQuery = $(document.body);
    jQuery.append("<br/>");
    for (var $i2 = 0, $l2 = fixtures.length, fixture = fixtures[$i2]; $i2 < $l2; $i2++, fixture = fixtures[$i2])
    {
        var methods = fixture.GetType().GetMethods();
        for (var $i3 = 0, $l3 = methods.length, method = methods[$i3]; $i3 < $l3; $i3++, method = methods[$i3])
        {
            if (method.get_Name().EndsWith$$String("Test"))
            {
                RunTest(jQuery, fixture, method);
            }
        }
    }
};
function RunTest(jQuery, fixture, method)
{
    var status = "OK";
    try
    {
        method.Invoke$$Object$$Object$Array(fixture, null);
    }
    catch (e)
    {
        status = "Failure: " + e;
    }
    jQuery.append(fixture.GetType().get_Name() + "." + method.get_Name() + ": " + status + "<br/>");
};
