/*Generated by SharpKit 5 v5.01.1000*/
function DefaultClient_Load()
{
    var paramExpr = SharpAlg.Native.Expr.Parameter("x");
    $(document.body).append(paramExpr.ParameterName + "Ready<br/>");
};
function btnTest_click(e)
{
    $(document.body).append("Hello world<br/>");
};
