/*Generated by SharpKit 5 v5.01.1000*/
if (typeof($CreateException)=='undefined') 
{
    var $CreateException = function(ex, error) 
    {
        if(error==null)
            error = new Error();
        if(ex==null)
            ex = new System.Exception.ctor();       
        error.message = ex.message;
        for (var p in ex)
           error[p] = ex[p];
        return error;
    }
}
if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var SharpAlg$Native$Number =
{
    fullname: "SharpAlg.Native.Number",
    baseTypeName: "System.Object",
    staticDefinition:
    {
        op_GreaterThanOrEqual: function (n1, n2)
        {
            return n1.get_Value() >= n2.get_Value();
        },
        op_Multiply: function (n1, n2)
        {
            return SharpAlg.Native.Number.FromDouble(n1.get_Value() * n2.get_Value());
        },
        op_Addition: function (n1, n2)
        {
            return SharpAlg.Native.Number.FromDouble(n1.get_Value() + n2.get_Value());
        },
        op_ExclusiveOr: function (n1, n2)
        {
            return SharpAlg.Native.Number.FromDouble(System.Math.Pow(n1.get_Value(), n2.get_Value()));
        },
        op_LessThanOrEqual: function (n1, n2)
        {
            throw $CreateException(new System.NotImplementedException.ctor(), new Error());
        },
        cctor: function ()
        {
            SharpAlg.Native.Number.Zero = null;
            SharpAlg.Native.Number.One = null;
            SharpAlg.Native.Number.MinusOne = null;
            SharpAlg.Native.Number.Zero = SharpAlg.Native.Number.FromDouble(0);
            SharpAlg.Native.Number.One = SharpAlg.Native.Number.FromDouble(1);
            SharpAlg.Native.Number.MinusOne = SharpAlg.Native.Number.FromDouble(-1);
        },
        FromDouble: function (value)
        {
            return new SharpAlg.Native.Number.ctor(value);
        },
        ToString$$Double: function (d)
        {
            return d.toString();
        }
    },
    assemblyName: "SharpAlg",
    Kind: "Class",
    definition:
    {
        ctor: function (value)
        {
            this._Value = 0;
            System.Object.ctor.call(this);
            this.set_Value(value);
        },
        Value$$: "System.Double",
        get_Value: function ()
        {
            return this._Value;
        },
        set_Value: function (value)
        {
            this._Value = value;
        },
        Equals$$Object: function (obj)
        {
            var other = As(obj, SharpAlg.Native.Number.ctor);
            return other != null && other.get_Value() == this.get_Value();
        },
        GetHashCode: function ()
        {
            return System.Object.commonPrototype.GetHashCode.call(this);
        },
        toString: function ()
        {
            return SharpAlg.Native.Number.ToString$$Double(this.get_Value());
        }
    }
};
JsTypes.push(SharpAlg$Native$Number);
