/*Generated by SharpKit 5 v5.01.1000*/
if (typeof(SharpAlg) == "undefined")
    var SharpAlg = {};
if (typeof(SharpAlg.Native) == "undefined")
    SharpAlg.Native = {};
SharpAlg.Native.PlatformHelper = function ()
{
};
SharpAlg.Native.PlatformHelper.ToInvariantString = function (d)
{
    return d.toString();
};
SharpAlg.Native.PlatformHelper.Parse = function (s)
{
    return System.Double.Parse$$String(s);
};
SharpAlg.Native.PlatformHelper.IntToChar = function (n)
{
    return String.fromCharCode(n);
};
SharpAlg.Native.PlatformHelper.CharToInt = function (c)
{
    return c.charCodeAt();
};
SharpAlg.Native.PlatformHelper.GetMessage = function (e)
{
    return e.toString();
};
