#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharpAlg.Android.UI.Resource", IsApplication=true)]

namespace SharpAlg.Android.UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			SharpAlg.Implementation.Resource.Drawable.monoandroidsplash = SharpAlg.Android.UI.Resource.Drawable.monoandroidsplash;
			SharpAlg.Implementation.Resource.String.ApplicationName = SharpAlg.Android.UI.Resource.String.ApplicationName;
			SharpAlg.Implementation.Resource.String.Hello = SharpAlg.Android.UI.Resource.String.Hello;
			SharpAlg.Implementation.Resource.Style.Mono_Android_Theme_Splash = SharpAlg.Android.UI.Resource.Style.Mono_Android_Theme_Splash;
			SharpAlg.Parser.Resource.Drawable.monoandroidsplash = SharpAlg.Android.UI.Resource.Drawable.monoandroidsplash;
			SharpAlg.Parser.Resource.String.ApplicationName = SharpAlg.Android.UI.Resource.String.ApplicationName;
			SharpAlg.Parser.Resource.String.Hello = SharpAlg.Android.UI.Resource.String.Hello;
			SharpAlg.Parser.Resource.Style.Mono_Android_Theme_Splash = SharpAlg.Android.UI.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int ExpressionTextBox = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ResultText = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
